/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldRouteImport } from './routes/yield'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecommendationRouteImport } from './routes/recommendation'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationRoute = RecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/recommendation': typeof RecommendationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/recommendation': typeof RecommendationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/recommendation': typeof RecommendationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yield': typeof YieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/history'
    | '/recommendation'
    | '/sitemap.xml'
    | '/yield'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/history'
    | '/recommendation'
    | '/sitemap.xml'
    | '/yield'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/history'
    | '/recommendation'
    | '/sitemap.xml'
    | '/yield'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  RecommendationRoute: typeof RecommendationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  YieldRoute: typeof YieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation': {
      id: '/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof RecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  RecommendationRoute: RecommendationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  YieldRoute: YieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
